# Generated by Django 5.2.6 on 2025-10-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_followers_customuser_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
