# Generated by Django 5.2.5 on 2025-09-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book'), ('can_create_book', 'Can create new book'), ('can_edit_book', 'Can edit existing book'), ('can_delete_book', 'Can delete existing book')]},
        ),
    ]
